// <auto-generated />
using System;
using ASP.NET_Hands_on.DatabseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424043626_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ho Chi Minh City",
                            Email = "phong.nguyen@example.com",
                            Gender = "Male",
                            Name = "Phong Nguyen",
                            Username = "phong.nguyen"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ha Noi",
                            Email = "minh.tran@example.com",
                            Gender = "Male",
                            Name = "Minh Tran",
                            Username = "minh.tran"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Da Nang",
                            Email = "linh.vo@example.com",
                            Gender = "Female",
                            Name = "Linh Vo",
                            Username = "linh.vo"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Can Tho",
                            Email = "hoang.le@example.com",
                            Gender = "Male",
                            Name = "Hoang Le",
                            Username = "hoang.le"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hue",
                            Email = "an.dang@example.com",
                            Gender = "Female",
                            Name = "An Dang",
                            Username = "an.dang"
                        });
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.DiscountDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DiscountDays");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.DiscountDayProduct", b =>
                {
                    b.Property<int>("DiscountDayId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("DiscountDayId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DiscountDayProducts");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 37500000m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 45000000m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 1200000m
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 1170000m
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 5,
                            OrderDate = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalPrice = 47200000m
                        });
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 1,
                            ProductId = 4,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 15,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 10,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 13,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 9,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = 5,
                            ProductId = 5,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop Asus ROG Strix",
                            Price = 35000000m,
                            ProductId = "LAP01"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop Dell XPS 15",
                            Price = 45000000m,
                            ProductId = "LAP02"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Laptop Lenovo ThinkPad",
                            Price = 28000000m,
                            ProductId = "LAP03"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bàn phím cơ Keychron K2",
                            Price = 2500000m,
                            ProductId = "ACC01"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chuột Logitech MX Master 3S",
                            Price = 2200000m,
                            ProductId = "ACC02"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Màn hình LG UltraGear 27\"",
                            Price = 8500000m,
                            ProductId = "ACC03"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 6500000m,
                            ProductId = "ACC04"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ổ cứng SSD Samsung 1TB",
                            Price = 3200000m,
                            ProductId = "ACC05"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ghế Ergonomic Herman Miller",
                            Price = 45000000m,
                            ProductId = "ACC06"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sách C# 12 and .NET 8",
                            Price = 650000m,
                            ProductId = "BOK01"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sách Clean Architecture",
                            Price = 550000m,
                            ProductId = "BOK02"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sách SQL Optimization",
                            Price = 480000m,
                            ProductId = "BOK03"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sách Angular & TypeScript",
                            Price = 520000m,
                            ProductId = "BOK04"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sách Python Data Science",
                            Price = 600000m,
                            ProductId = "BOK05"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Gói NovelAI Premium (Tháng)",
                            Price = 600000m,
                            ProductId = "SUB01"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Gói Last Origin Monthly Pass",
                            Price = 350000m,
                            ProductId = "SUB02"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Bản quyền JetBrains Rider",
                            Price = 3800000m,
                            ProductId = "SFT01"
                        },
                        new
                        {
                            Id = 18,
                            Name = "OpenAI API Credits",
                            Price = 1200000m,
                            ProductId = "SFT02"
                        },
                        new
                        {
                            Id = 19,
                            Name = "PaddleOCR Pro License",
                            Price = 5000000m,
                            ProductId = "SFT03"
                        },
                        new
                        {
                            Id = 20,
                            Name = "GitHub Copilot (Năm)",
                            Price = 2500000m,
                            ProductId = "SFT04"
                        });
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.DiscountDayProduct", b =>
                {
                    b.HasOne("ASP.NET_Hands_on.Domain.Model.DiscountDay", "DiscountDay")
                        .WithMany("DiscountDayProducts")
                        .HasForeignKey("DiscountDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_Hands_on.Domain.Model.Product", "Product")
                        .WithMany("DiscountDayProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscountDay");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.Order", b =>
                {
                    b.HasOne("ASP.NET_Hands_on.Domain.Model.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.OrderProduct", b =>
                {
                    b.HasOne("ASP.NET_Hands_on.Domain.Model.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NET_Hands_on.Domain.Model.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.DiscountDay", b =>
                {
                    b.Navigation("DiscountDayProducts");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("ASP.NET_Hands_on.Domain.Model.Product", b =>
                {
                    b.Navigation("DiscountDayProducts");

                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
